### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ItzFel** [NgLam2911/InvCraft#12]
Hello, I want to report back with a problem the recipe doesn't work after the server restarts. and I have used the latest build version and it still doesn't work I have to create a new recipe for it to work, Should I delete the old plugin_data?

**Comment by NgLam2911** [comment]
Can you show your plugin version ? or ... make sure you are at 0.1.1

**Comment by ItzFel** [comment]
![1231](https://user-images.githubusercontent.com/62336632/113226451-d0d71780-92c2-11eb-866c-13351fc3306b.PNG)

**Comment by ItzFel** [comment]
I have used the latest version and it still doesn't work

**Comment by NgLam2911** [comment]
Try to reinstall this plugin, make sure you have removed all InvCraft data.
