### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ItzFel** [NgLam2911/InvCraft#14]
non-op cant craft the recipe I made but if I am the OP I can craft the recipe I made

**Comment by NgLam2911** [comment]
Did you try to craft it again without op ?

**Comment by NgLam2911** [comment]
As i know that i doesn't add permission limit to craft menu.

**Comment by ItzFel** [comment]
> Did you try to craft it again without op ?

still not able

**Comment by ItzFel** [comment]
will you fix this?

**Comment by NgLam2911** [comment]
> will you fix this?

I will try to reslove this problem and find what the main reason of this problem...

**Comment by NgLam2911** [comment]
Did you try to remove all plugin except this plugin, this issues still occurs ?

**Comment by ItzFel** [comment]
> Did you try to remove all plugin except this plugin, this issues still occurs ?

I have removed all the plugins but still not working

**Comment by NgLam2911** [comment]
Maybe this bug is related to item NBT, try to craft item in edit recipe and doesnt related to permission.
I will reopen if i found something new.
