### ISSUE TITLE
Plugin Don't show

### ISSUE THREAD

**Issue by Satyamss76** [NgLam2911/InvCraft#17]
Plugin is not showing please fix it up as soon as possible ;( please and plugin is best I have tries older version but newer is not showing

**Comment by NgLam2911** [comment]
Please give more info:
- PocketMine-MP Version
- PHP Version
- Plugin version

* For PocketMine-MP 3.x.y, please download plugin from poggit.
Sorry for late respond.

**Comment by Satyamss76** [comment]
Plugin is not showing 3.22.1 or after it is not showing in game i am using pocketmine if you can fix it

**Comment by NgLam2911** [comment]
Sorry, i dont have enough infomation about this bug, please open another issues with more infomation.
