### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GamerMJay** [NgLam2911/InvCraft#21]
[18:05:45.574] [Server thread/CRITICAL]: ErrorException: "Undefined array key 9" (EXCEPTION) in "plugins/InvCraft.phar/src/NgLamVN/InvCraft/Recipe" at line 51

--- Stack trace ---

#0 plugins/InvCraft.phar/src/NgLamVN/InvCraft/Recipe(51): pocketmine\errorhandler\ErrorToExceptionHandler::handle(integer 2, string[21] Undefined array key 9, string[76] phar:///home/minecraft/plugins/InvCraft.phar/src/NgLamVN/InvCraft/Recipe.php, integer 51)

#1 plugins/InvCraft.phar/src/NgLamVN/InvCraft/menu/CraftMenu(68): NgLamVN\InvCraft\Recipe->equal(array[9])

#2 plugins/InvCraft.phar/src/NgLamVN/InvCraft/libs/muqsit/invmenu/InvMenuEventHandler(120): NgLamVN\InvCraft\menu\CraftMenu->NgLamVN\InvCraft\menu\{closure}(object ipad54\netherblocks\player\Player#116396)

#3 plugins/InvCraft.phar/src/NgLamVN/InvCraft/libs/muqsit/invmenu/session/network/PlayerNetwork(123): NgLamVN\InvCraft\libs\muqsit\invmenu\InvMenuEventHandler::NgLamVN\InvCraft\libs\muqsit\invmenu\{closure}(true)

#4 plugins/InvCraft.phar/src/NgLamVN/InvCraft/libs/muqsit/invmenu/session/network/PlayerNetwork(135): NgLamVN\InvCraft\libs\muqsit\invmenu\session\network\PlayerNetwork->processCurrent(true)

#5 plugins/InvCraft.phar/src/NgLamVN/InvCraft/libs/muqsit/invmenu/InvMenuEventHandler(32): NgLamVN\InvCraft\libs\muqsit\invmenu\session\network\PlayerNetwork->notify(integer 881937352000)

#6 pmsrc/src/event/RegisteredListener(75): NgLamVN\InvCraft\libs\muqsit\invmenu\InvMenuEventHandler->onDataPacketReceive(object pocketmine\event\server\DataPacketReceiveEvent#207052)

#7 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketReceiveEvent#207052)

#8 pmsrc/src/network/mcpe/NetworkSession(396): pocketmine\event\Event->call()

#9 pmsrc/src/network/mcpe/NetworkSession(360): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\NetworkStackLatencyPacket#206188, string[10] s@..W.....)

#10 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[13] .*v`..~......)

#11 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[22] .......q...Y...A2.qD..)

#12 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#114462)

#13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()

#14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()

#15 pmsrc/src/Server(1660): pocketmine\snooze\SleeperHandler->sleepUntil(double 1647536745.6057)

#16 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()

#17 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)

#18 pmsrc/src/PocketMine(327): pocketmine\server()

#19 pmsrc(11): require(string[57] phar:///home/minecraft/pocketmine.phar/src/PocketMine.php)

--- End of exception information ---

**Comment by NgLam2911** [comment]
Do you have any way to reproduce this error ?

**Comment by GamerMJay** [comment]
I already managed it but I have one request, can you do it in such a way that the recipes remain saved after the restart?

**Comment by NgLam2911** [comment]
> I already managed it but I have one request, can you do it in such a way that the recipes remain saved after the restart?

So u mean after the server got crashed?

**Comment by NgLam2911** [comment]
> I already managed it but I have one request, can you do it in such a way that the recipes remain saved after the restart?

I think you should open another issues for this problem...
