### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by GamerMJay** [NgLam2911/InvCraft#22]
Hello, can you make it so that the recipes are saved after restarting the server? That would be very sweet of you.

**Comment by NgLam2911** [comment]
I don't know what you mean, but maybe it's work like saving a recipe to a file after adding or editing it...

Hmm just call `Provider::save()` bruh

**Comment by GamerMJay** [comment]
so if i create a recipe and then hit save and then restart the server it's gone means i have to add it back after every restart

**Comment by GamerMJay** [comment]
?

**Comment by GamerMJay** [comment]
Pls help

**Comment by GamerMJay** [comment]
So I'll sum it up correctly. I create a new recipe and when I restart my server the recipe is gone so it was automatically deleted? It's on my localhost And on my main server like this... Please help

**Comment by NgLam2911** [comment]
> So I'll sum it up correctly. I create a new recipe and when I restart my server the recipe is gone so it was automatically deleted? It's on my localhost And on my main server like this... Please help

Basically, everything will be saved after `stop` command

**Comment by GamerMJay** [comment]
Mhm that's kind of stupid.. Could you maybe change that?

**Comment by NgLam2911** [comment]
> Mhm that's kind of stupid.. Could you maybe change that?

Planned in rewrite version.

**Comment by GamerMJay** [comment]
Okay Thanks! 👍
