### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dadevguy** [NgLam2911/InvCraft#25]
So when i type  `/invcraft view <a>`
 i got redirected to invcraft main menu please fix this bug

**Comment by NgLam2911** [comment]
> So when i type `/invcraft view <a>` i got redirected to invcraft main menu please fix this bug

Thanks for your report ... its really annoying ...

**Comment by NgLam2911** [comment]
Make sure you are using the latest version of InvCraft... Currently, I can't reproduce this issue.
If you are using the latest version and still have this problem, please give more information like images or videos.
