### ISSUE TITLE
[Idea] Add...

### ISSUE THREAD

**Issue by dadevguy** [NgLam2911/InvCraft#26]
## Please Add A Feature Like 
* /invcraft 3x3 To Open 3x3 Crafting Table Directly
* /invcraft 6x6 To Open 6x6 Crafting Table

**Comment by NgLam2911** [comment]
> ## Please Add A Feature Like
> * /invcraft 3x3 To Open 3x3 Crafting Table Directly
> * /invcraft 6x6 To Open 6x6 Crafting Table

Ya, i just already put everything in a simple UI, but its look good...

**Comment by NgLam2911** [comment]
Maybe I will implement this after rewriting this plugin.

**Comment by dadevguy** [comment]
ok

**Comment by dadevguy** [comment]
Hey I Really Need This Feature Now

**Comment by NgLam2911** [comment]
> Hey I Really Need This Feature Now

Sorry, currently i'm really busy at school...

**Comment by dadevguy** [comment]
ok, i can understand bro ❤️

**Comment by NgLam2911** [comment]
planning for rewrite soon.
