### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dadevguy** [NgLam2911/InvCraft#29]
```yaml
 [Server thread/CRITICAL]: Error: "Class "JinodkDevTeam\utils\ItemUtils" not found" (EXCEPTION) in "plugins/InvCraft/src/NgLamVN/InvCraft/Loader" at line 100
```

i am getting this error

**Comment by NgLam2911** [comment]
There are some ways to fix this problem:
* Download this plugin from poggit or poggit builds.
* Add every virion library used in InvCraft (listed in poggit.yml) to your server and use DEVirion.
