### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by KarTonKai** [NgLam2911/InvCraft#30]
Update to pm5 !!

**Comment by NgLam2911** [comment]
loading for pm5 ...

**Comment by GabBiswajit** [comment]
Thanks ❤️

**Comment by NgLam2911** [comment]
Plugin have been updated by @GabBiswajit , check the branch pm5 for more info, i'm currently dont have time to test it, if u found any issues related to this plugin, feel free to open other issues.
