### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by GamerMJay** [NgLam2911/InvCraft#34]
Fatal error: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of NgLamVN\InvCraft\libs\jojoe77777\FormAPI\Form::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar://D:/PocketMine/PM5/plugins/InvCraft_dev-40.phar/src/NgLamVN/InvCraft/libs/jojoe77777/FormAPI/Form.php:53
Stack trace:
#0 phar://D:/PocketMine/PM5/plugins/InvCraft_dev-40.phar/src/NgLamVN/InvCraft/libs/jojoe77777/FormAPI/Form.php(10): pocketmine\errorhandler\ErrorToExceptionHandler::handle(8192, 'Return type of ...', 'phar://D:/Pocke...', 53)
#1 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/thread/ThreadSafeClassLoader.php(133): include('phar://D:/Pocke...')
#2 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/thread/ThreadSafeClassLoader.php(123): pocketmine\thread\ThreadSafeClassLoader->loadClass('NgLamVN\\InvCraf...')
#3 phar://D:/PocketMine/PM5/plugins/InvCraft_dev-40.phar/src/NgLamVN/InvCraft/libs/jojoe77777/FormAPI/SimpleForm.php(7): pocketmine\thread\ThreadSafeClassLoader->pocketmine\thread\{closure}('NgLamVN\\InvCraf...')
#4 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/thread/ThreadSafeClassLoader.php(133): include('phar://D:/Pocke...')
#5 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/thread/ThreadSafeClassLoader.php(123): pocketmine\thread\ThreadSafeClassLoader->loadClass('NgLamVN\\InvCraf...')
#6 phar://D:/PocketMine/PM5/plugins/InvCraft_dev-40.phar/src/NgLamVN/InvCraft/ui/AdminUI.php(24): pocketmine\thread\ThreadSafeClassLoader->pocketmine\thread\{closure}('NgLamVN\\InvCraf...')
#7 phar://D:/PocketMine/PM5/plugins/InvCraft_dev-40.phar/src/NgLamVN/InvCraft/ui/AdminUI.php(20): NgLamVN\InvCraft\ui\AdminUI->form(Object(pocketmine\player\Player))
#8 phar://D:/PocketMine/PM5/plugins/InvCraft_dev-40.phar/src/NgLamVN/InvCraft/command/InvCraftCommand.php(41): NgLamVN\InvCraft\ui\AdminUI->__construct(Object(pocketmine\player\Player))
#9 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/command/SimpleCommandMap.php(212): NgLamVN\InvCraft\command\InvCraftCommand->execute(Object(pocketmine\player\Player), 'invcraft', Array)
#10 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/Server.php(1416): pocketmine\command\SimpleCommandMap->dispatch(Object(pocketmine\player\Player), 'invcraft')
#11 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/player/Player.php(1512): pocketmine\Server->dispatchCommand(Object(pocketmine\player\Player), 'invcraft')
#12 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/network/mcpe/handler/InGamePacketHandler.php(826): pocketmine\player\Player->chat('/invcraft')
#13 phar://D:/PocketMine/PM5/PocketMine-MP.phar/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket.php(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(Object(pocketmine\network\mcpe\protocol\CommandRequestPacket))
#14 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/network/mcpe/NetworkSession.php(445): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(Object(pocketmine\network\mcpe\handler\InGamePacketHandler))
#15 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/network/mcpe/NetworkSession.php(383): pocketmine\network\mcpe\NetworkSession->handleDataPacket(Object(pocketmine\network\mcpe\protocol\CommandRequestPacket), 'M\t/invcraft\x00(@\x17...')
#16 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/network/mcpe/raklib/RakLibInterface.php(219): pocketmine\network\mcpe\NetworkSession->handleEncoded('\x93\xF7\xE5\xD4\xCF\xCC+K.JL+a\xD0p...')
#17 phar://D:/PocketMine/PM5/PocketMine-MP.phar/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver.php(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(0, '\xFE3,5>\x82\x8D\xC4\x13\x18\x93\xD7\x12\xD3\x10...')
#18 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/network/mcpe/raklib/RakLibInterface.php(111): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(Object(pocketmine\network\mcpe\raklib\RakLibInterface))
#19 phar://D:/PocketMine/PM5/PocketMine-MP.phar/vendor/pocketmine/snooze/src/SleeperHandler.php(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#20 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/TimeTrackingSleeperHandler.php(58): pocketmine\snooze\SleeperHandler->processNotifications()
#21 phar://D:/PocketMine/PM5/PocketMine-MP.phar/vendor/pocketmine/snooze/src/SleeperHandler.php(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#22 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/Server.php(1681): pocketmine\snooze\SleeperHandler->sleepUntil(1694888217.865)
#23 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/Server.php(1064): pocketmine\Server->tickProcessor()
#24 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/PocketMine.php(334): pocketmine\Server->__construct(Object(pocketmine\thread\ThreadSafeClassLoader), Object(pocketmine\utils\MainLogger), 'D:\\PocketMine\\P...', 'D:\\PocketMine\\P...')
#25 phar://D:/PocketMine/PM5/PocketMine-MP.phar/src/PocketMine.php(357): pocketmine\server()
#26 D:\PocketMine\PM5\PocketMine-MP.phar(11): require('phar://D:/Pocke...')
#27 {main} in phar://D:/PocketMine/PM5/plugins/InvCraft_dev-40.phar/src/NgLamVN/InvCraft/libs/jojoe77777/FormAPI/Form.php on line 10

**Comment by GabBiswajit** [comment]
@GamerMJay we already removed libs from plugin and if you talking about pm4 than we don't give support for pm4 anymore use pm5 version.
Thanks.

**Comment by GamerMJay** [comment]
@GabBiswajit i use PocketMine-MP 5

**Comment by GabBiswajit** [comment]
@GamerMJay there is no `NgLamVN\InvCraft\libs\jojoe77777\FormAPI\Form::jsonSerialize()`

**Comment by GabBiswajit** [comment]
@GamerMJay if you use a fork or updete by self than we unable to support you.

**Comment by GamerMJay** [comment]
I use these following virions 

https://github.com/NgLam2911/InvCraft/blob/pm5/.poggit.yml

**Comment by GabBiswajit** [comment]
Are you sure you use last version on FormAPI ??

**Comment by GabBiswajit** [comment]
I can only help if you use this version : https://github.com/NgLam2911/InvCraft

**Comment by GamerMJay** [comment]
i use this FormAPI version

https://poggit.pmmp.io/ci/jojoe77777/FormAPI/libFormAPI

**Comment by GabBiswajit** [comment]
I see but you don't use perfect version off invcraft https://github.com/NgLam2911/InvCraft use this

**Comment by GamerMJay** [comment]
I'm using the latest build version

https://poggit.pmmp.io/r/223223/InvCraft_dev-41.phar

**Comment by GamerMJay** [comment]
I'm using the latest build version

https://poggit.pmmp.io/r/223223/InvCraft_dev-41.phar

**Comment by GamerMJay** [comment]
I'll try it again soon

**Comment by GamerMJay** [comment]
I'll try it again soon

**Comment by GamerMJay** [comment]
[Sun_Sep_17-09.26.44-BST_2023.log](https://github.com/NgLam2911/InvCraft/files/12642362/Sun_Sep_17-09.26.44-BST_2023.log)

i created a new pocketmine 5 server

**Comment by GabBiswajit** [comment]
@GamerMJay it's same buddy I already say you that libs in plugin

**Comment by GabBiswajit** [comment]
Wait what

**Comment by GabBiswajit** [comment]
[invcraft.zip](https://github.com/NgLam2911/InvCraft/files/12642870/invcraft.zip)
I Unable to send a phar so convert it to phar your self and try it

**Comment by GabBiswajit** [comment]
@GamerMJay is that slove ?

**Comment by NgLam2911** [comment]
Fixed at lib update commit.
