### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EvilerDragon634** [NgLam2911/InvCraft#37]
Thread: Main
Error: Call to undefined method pocketmine\item\Item::hasAnyDamageValue()
File: plugins/InvCraft_dev-42.phar/src/NgLamVN/InvCraft/libs/JinodkDevTeam/utils/ItemUtils
Line: 54

**Comment by NgLam2911** [comment]
yep.. another library bug, since this change is affect to file save format so its may take a little bit of times
btw the newest pm doesnt have that function anymore...

**Comment by NgLam2911** [comment]
maybe a patch will be added today after few hours since i'm still busssyyyyyyyy

**Comment by GabBiswajit** [comment]
@NgLam2911 still not ?? 
I also busy to fix this and I also need the plugin can you do ??

**Comment by GabBiswajit** [comment]
`Item::hasAnyDamageValue()` has been removed

**Comment by GabBiswajit** [comment]
`pocketmine\crafting\MetaWildcardRecipeIngredient` it well work

**Comment by GabBiswajit** [comment]
@NgLam2911 done now it's fix check the `FI-Utils`  I Just Create A `Pull requests
1` And It's Work I Will Test 🐱
