### ISSUE TITLE
Recipe

### ISSUE THREAD

**Issue by sh-codes101** [NgLam2911/InvCraft#40]
Recipe not saving after restarting server in your old pm5 Invcraft version 
[InvCraft-pm5.zip](https://github.com/user-attachments/files/16568670/InvCraft-pm5.zip)
here it is ....

**Comment by NgLam2911** [comment]
I'm no longer working on old pm5 version also saving doesnt work in pm5 port from original pm4 version...
i will close this after finished rewrite version

**Comment by sh-codes101** [comment]
ohk

**Comment by NgLam2911** [comment]
Fixed in rewrite version !
