### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by sh-codes101** [NgLam2911/InvCraft#42]
9176b2494a4a84729f9cc4dd1f75dd3ec2c8618d
PHP version: 8.2.17
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: InvCraft

Thread: Main
Error: Undefined array key 0
File: plugins/InvCraft_dev-70.phar/src/NgLam2911/InvCraft/ui/forms/ListRecipeForm
Line: 25
Type: ErrorException
Backtrace:
#0 plugins/InvCraft_dev-70.phar/src/NgLam2911/InvCraft/ui/forms/ListRecipeForm(25): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[21] Undefined array key 0, string[102] phar:///home/container/plugins/InvCraft_dev-70.phar/src/NgLam2911/InvCraft/ui/fo, int 25)
#1 plugins/InvCraft_dev-70.phar/src/NgLam2911/InvCraft/libs/_5753972eb36c8972/dktapps/pmforms/MenuForm(90): NgLam2911\InvCraft\ui\forms\ListRecipeForm->NgLam2911\InvCraft\ui\forms\{closure}(object pocketmine\player\Player#65305, int 0)
#2 pmsrc/src/player/Player(2143): NgLam2911\InvCraft\libs\_5753972eb36c8972\dktapps\pmforms\MenuForm->handleResponse(object pocketmine\player\Player#65305, int 0)
#3 pmsrc/src/network/mcpe/handler/InGamePacketHandler(975): pocketmine\player\Player->onFormSubmit(int 5, int 0)
#4 pmsrc/vendor/pocketmine/bedrock-protocol/src/ModalFormResponsePacket(63): pocketmine\network\mcpe\handler\InGamePacketHandler->handleModalFormResponse(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#96611)
#5 pmsrc/src/network/mcpe/NetworkSession(469): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#190606)
#6 pmsrc/src/network/mcpe/NetworkSession(407): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#96611, string[7] e...0..)
#7 pmsrc/src/network/mcpe/raklib/RakLibInterface(214): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[9] ..e...0..)
#8 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[18] ......H.8.n...ZjGG)
#9 pmsrc/src/network/mcpe/raklib/RakLibInterface(107): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#176205) when I do save button the menu doesn't close _**&**_ when I view recipe it gives this error

**Comment by NgLam2911** [comment]
Fixed in last commit for the error in crash report
